- src: git@github.com:o2-priority/ansible-docker.git
  version: master
  scm: git
  name: o2-priority.docker

- src: git@github.com:o2-priority/ansible-consul.git
  version: master
  scm: git
  name: o2-priority.consul