---

- name: Check connection to registrator service registry
  wait_for: host={{ registrator_service_registry_host }} port={{ registrator_service_registry_port }}

- name: Start registrator
  docker:
    name:  registrator
    image: gliderlabs/registrator
    hostname: "{{ registrator_hostname }}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip {{ registrator_ip }} consul://{{ registrator_service_registry_address }}
    state: started
  tags: [consul]

- name: Start registrator KV
  docker:
    name:  registrator-kv
    image: gliderlabs/registrator
    hostname: "{{ registrator_hostname }}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip {{ registrator_ip }} consulkv://{{ registrator_service_registry_address }}/services
    state: started
  tags: [consul]
