---

- name: Validate registrator service registry
  fail: msg="{{ registrator_service_registry_backend }} service registry specified not supported by this role yet."
  when: not registrator_service_registry_backend | match("consul")

- include_tasks: "{{ registrator_service_registry_backend }}.yml"
